# Generated by Django 4.2.1 on 2023-05-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('login', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DomainNameServer',
            fields=[
                ('address', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='homework.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='dns_server',
            field=models.ManyToManyField(blank=True, to='homework.domainnameserver'),
        ),
    ]
