# Generated by Django 4.2.1 on 2023-05-09 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 14, 17, 37, 43352)),
        ),
    ]
